name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test-python36:
    uses: vikinganalytics/daeploy-s2i-python/.gitub/workflows/ci_check_image.yml@master
    with:
      imagename: python36-slim
  test-python37:
    uses: vikinganalytics/daeploy-s2i-python/.gitub/workflows/ci_check_image.yml@master
    with:
      imagename: python37-slim
  test-python38:
    uses: vikinganalytics/daeploy-s2i-python/.gitub/workflows/ci_check_image.yml@master
    with:
      imagename: python38-slim
  test-python39:
    uses: vikinganalytics/daeploy-s2i-python/.gitub/workflows/ci_check_image.yml@master
    with:
      imagename: python39-slim
