name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test-python38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install s2i"
        run: |
          wget -c https://github.com/openshift/source-to-image/releases/download/v1.3.0/source-to-image-v1.3.0-eed2850f-linux-amd64.tar.gz -O - | tar -xz
          sudo cp s2i /usr/local/bin
      - name: Run the test script
        run: make test -C python38-slim/
  test-python39:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install s2i"
        run: |
          wget -c https://github.com/openshift/source-to-image/releases/download/v1.3.0/source-to-image-v1.3.0-eed2850f-linux-amd64.tar.gz -O - | tar -xz
          sudo cp s2i /usr/local/bin
      - name: Run the test script
        run: make test -C python39-slim/

