name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test-python38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the test script
        run: make test -C python38-slim/
