name: Test S2I Builder Image

on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string

jobs:
  test-s2i-builder-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install s2i"
        run: |
          wget -c https://github.com/openshift/source-to-image/releases/download/v1.3.0/source-to-image-v1.3.0-eed2850f-linux-amd64.tar.gz -O - | tar -xz
          sudo cp s2i /usr/local/bin
      - name: Run the test script
        run: make test -C ${{ inputs.imagename }}
