name: Release docker image

on:
  release:
    types: [published]

jobs:

  build:
    name: Build and run daeploy Manager
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DAEPLOY_DOCKER_USERNAME }}
        password: ${{ secrets.DAEPLOY_DOCKER_PASSWORD }}

    - name: Docker build and push
      run: |
        docker build -t daeploy/s2i-python:3.8-slim-${{ github.event.release.tag_name }} -t daeploy/s2i-python:latest ./python38-slim
        docker push --all-tags daeploy/s2i-python